apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-out-task
spec:
  results:
  - description: /tmp/output
    name: output
  params:
    - name: buildnumber
      description: test
    - name: secprop
      description: test   
  steps:
    - name: task-two-step-four
      image: ubuntu
      env:
        - name: BUILD_NUMBER
          value: $(params.buildnumber)
        - name: SEC_PROP
          value: $(params.secprop)
      command: ['bash']
      args: ['-c', 'echo "secprop $SEC_PROP" && echo "secprop $SEC_PROP" && echo "secprop $SEC_PROP" && echo "secprop $SEC_PROP" | tee $(results.output.path)'] 
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-out-task-script
spec:
  params:
    - name: buildnumber
      description: test
    - name: secprop
      description: test   
    - name: prevout
      description: test
  steps:
    - name: scriptstep
      image: ubuntu
      env:
        - name: BUILD_NUMBER
          value: $(params.buildnumber)
        - name: PREV
          value: $(params.prevout)
        - name: SEC_PROP
          value: $(params.secprop)
      script: |
        #!/bin/bash
        echo "previs $PREV"
        echo "test script value $SEC_PROP"
        exit 0

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: buildnumber
      description: the pipeline pvc name
    - name: secprop
      description: test
  tasks:
    - name: sample-out-task
      taskRef:
        name: sample-out-task
      params:
        - name: buildnumber
          value: $(params.buildnumber)
        - name: secprop
          value: $(params.secprop)
    - name: sample-out-task-script
      taskRef:
        name: sample-out-task-script
      params:
        - name: buildnumber
          value: $(params.buildnumber)
        - name: prevout
          value: $(tasks.sample-out-task.results.output)
        - name: secprop
          value: $(params.secprop)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: buildnumber
      description: thebuildnuminput
      default: buildnumberfailedjerh
    - name: secprop
      description: secval
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
        params:
        - name: buildnumber
          value: $(params.buildnumber)
        - name: secprop
          value: $(params.secprop)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: buildnumber
      value: $(header.x-github-event)
    - name: revision
      value: "master"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template
