apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-out-task
spec:
  params:
    - name: buildnumber
      description: test
    - name: secprop
      description: test   
  steps:
    - name: task-two-step-four
      image: ubuntu
      env:
        - name: BUILD_NUMBER
          value: $(params.buildnumber)
        - name: SEC_PROP
          value: $(params.secprop)
      command: ['bash']
      args: ['-c', 'for i in {1..3}; do echo $BUILD_NUMBER 2 && sleep 3 && echo $SEC_PROP ; done;'] 
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-out-task-script
spec:
  params:
    - name: buildnumber
      description: test
    - name: secprop
      description: test   
  steps:
    - name: scriptstep
      image: ubuntu
      env:
        - name: BUILD_NUMBER
          value: $(params.buildnumber)
        - name: SEC_PROP
          value: $(params.secprop)
       script: |
        #!/bin/bash
        echo "test script value $SEC_PROP"
        exit 0
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: buildnumber
      description: the pipeline pvc name
    - name: secprop
      description: test
  tasks:
    - name: sample-out-task
      taskRef:
        name: sample-out-task
      params:
        - name: buildnumber
          value: $(params.buildnumber)
        - name: secprop
          value: $(params.secprop)
    - name: sample-out-task-script
      taskRef:
        name: sample-out-task-script
      params:
        - name: buildnumber
          value: $(params.buildnumber)
        - name: secprop
          value: $(params.secprop)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: buildnumber
      description: thebuildnuminput
      default: buildnumberfailedjerh
    - name: secprop
      description: secval
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
        params:
        - name: buildnumber
          value: $(params.buildnumber)
        - name: secprop
          value: $(params.secprop)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: repository
      value: "https://github.com/open-toolchain/hello-tekton"
    - name: revision
      value: "master"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template
