apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task1
spec:
  inputs:
    params:
      - name: securetest
        description: securetest
      - name: environment
        description: environment
      - name: region
        description: region
  steps:
  - name: task-one-step-one
    env:
      - name: SECURE_TEST
        value: $(inputs.params.securetest)
      - name: ENV
        value: $(inputs.params.environment)
      - name: REGION
        value: $(inputs.params.region)
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'echo $SECURE_TEST && echo $ENV && echo $REGION'] # tests that targetpath works
  - name: task-one-step-two
    image: ubuntu
    command: ['bash']
    args: ['-c', 'for i in {1..2}; do echo GONLOGGIN 2 && sleep 1; done;'] 
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task2
spec:
  steps:
  - name: task-two-step-one
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'for i in {1..2}; do echo GONLOGGIN 1 && sleep 1; done;'] # tests that targetpath works
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: 999-working-logs-long
spec:
  params:
    - name: securetest
      description: securetest
    - name: environment
      description: environment
    - name: region
      description: region
  tasks:
  - name: task1
    taskRef:
      name: task1
    params:
      - name: securetest
        value: $(params.securetest)
      - name: environment
        value: $(params.environment)
      - name: region
        value: $(params.region)
  - name: task2
    taskRef:
      name: task2
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: message
      description: The message to print
      default: This is the default message
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: cutting-down-trees-run
        labels:
          triggertemplated: "true"
          generatedBy: "triggers-example"
      spec:
        pipelineRef:
          name: 999-working-logs-long
        params:
        - name: repository
          value: $(params.securetest)
        - name: revision
          value: $(params.revision)
        - name: apikey
          value: $(params.apikey)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-binding
spec:
  params:
    - name: gitrevision
      value: $(event.head_commit.id)
    - name: gitrepositoryurl
      value: $(event.repository.url)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: manual-pipeline-binding
spec:
  params:
    - name: gitrevision
      value: v0.32.0
    - name: gitrepositoryurl
      value: https://github.com/GoogleContainerTools/skaffold
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: pipeline-binding
      template:
        name: pipeline-template
      params:
        - name: message
          value: Hello from the Git Triggers EventListener!
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: manual-listener
spec:
  triggers:
    - binding:
        name: manual-pipeline-binding
      template:
        name: pipeline-template
      params:
        - name: message
          value: Hello from the Manual Triggers EventListener!
